# Generated by Django 3.2.16 on 2023-09-03 20:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DisplayDetail',
            fields=[
                ('Display_ID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Display_MAC', models.CharField(max_length=50)),
                ('EPD_No', models.CharField(max_length=20)),
                ('Activation_Date', models.DateField()),
                ('Initial_IP', models.CharField(max_length=50)),
                ('Current_IP', models.CharField(max_length=50)),
                ('Is_Active', models.BooleanField()),
                ('Display_Size', models.CharField(max_length=50)),
                ('EPDs_Nos', models.CharField(max_length=20)),
                ('Temp_Sensor', models.BooleanField()),
                ('Humidity_Sensor', models.BooleanField()),
                ('Presence_Sensor', models.BooleanField()),
                ('Light_Sensor', models.BooleanField()),
                ('BLE_Receiver', models.BooleanField()),
                ('Memory_Size', models.CharField(max_length=50)),
                ('LoRa_Comms', models.CharField(max_length=50)),
                ('Wifi_Comms', models.CharField(max_length=50)),
                ('Last_Message', models.CharField(max_length=50)),
                ('Last_Image', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FTPAddress',
            fields=[
                ('FTP_Address', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Date', models.DateField()),
                ('Time', models.TimeField()),
                ('URL', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LocationIdentifier',
            fields=[
                ('Location_Identifier_ID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Branch_Name', models.CharField(max_length=100)),
                ('Branch_Location', models.CharField(max_length=100)),
                ('Specific_Location', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('Customer_ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('Company_Name', models.CharField(default='', max_length=200)),
                ('email', models.EmailField(default='', max_length=50, unique=True)),
                ('Main_Address', models.CharField(default='', max_length=100)),
                ('Primary_Contact', models.CharField(default='', max_length=50)),
                ('Primary_Phone', models.CharField(default='', max_length=50)),
                ('Customer_Type', models.CharField(default='', max_length=50)),
                ('Registration_Date', models.DateField(default=django.utils.timezone.now)),
                ('Services_Detail', models.CharField(default='abcdef', max_length=100)),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ViewerDetail',
            fields=[
                ('Viewer_ID', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Gender', models.CharField(max_length=20)),
                ('Age', models.IntegerField()),
                ('Nationality', models.CharField(max_length=50)),
                ('Course', models.CharField(max_length=50)),
                ('Accommodation_Type', models.CharField(max_length=50)),
                ('Location_Identifier_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Personalization.locationidentifier')),
            ],
        ),
        migrations.CreateModel(
            name='StaffCustomer',
            fields=[
                ('User_ID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Username', models.CharField(max_length=50)),
                ('Password', models.CharField(max_length=50)),
                ('First_Name', models.CharField(max_length=50)),
                ('Last_Name', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=50)),
                ('Address', models.CharField(max_length=50)),
                ('Phone', models.CharField(max_length=11)),
                ('Initial_IP', models.CharField(max_length=50)),
                ('Current_IP', models.CharField(max_length=50)),
                ('Is_Active', models.BooleanField()),
                ('Location_Identifier_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Personalization.locationidentifier')),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('Message_ID', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Date', models.DateField()),
                ('Time', models.TimeField()),
                ('Age', models.IntegerField()),
                ('Gender', models.CharField(max_length=10)),
                ('Message', models.CharField(max_length=50)),
                ('Message_Parameters', models.CharField(max_length=50)),
                ('Display_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Personalization.displaydetail')),
                ('Location_Identifier_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Personalization.locationidentifier')),
            ],
        ),
        migrations.AddField(
            model_name='locationidentifier',
            name='Customer_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('Image_ID', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Age', models.IntegerField()),
                ('Gender', models.CharField(max_length=50)),
                ('Image_Parameters', models.CharField(max_length=50)),
                ('URL', models.CharField(max_length=100)),
                ('Display_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Personalization.displaydetail')),
                ('FTP_Address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Personalization.ftpaddress')),
            ],
        ),
        migrations.AddField(
            model_name='ftpaddress',
            name='Location_Identifier_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Personalization.locationidentifier'),
        ),
        migrations.AddField(
            model_name='displaydetail',
            name='Location_Identifier_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Personalization.locationidentifier'),
        ),
    ]
