# Generated by Django 3.2.16 on 2023-09-04 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personalization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationidentifier',
            name='Specific_Location',
            field=models.CharField(max_length=100),
        ),
    ]
