# Generated by Django 3.2.16 on 2023-09-04 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personalization', '0002_alter_locationidentifier_specific_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='displaydetail',
            name='Display_ID',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='locationidentifier',
            name='Location_Identifier_ID',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
