# Generated by Django 3.2.16 on 2023-09-04 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personalization', '0004_alter_messages_message_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewerdetail',
            name='Viewer_ID',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
