# Generated by Django 3.2.16 on 2023-09-05 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personalization', '0005_alter_viewerdetail_viewer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ftpaddress',
            name='FTP_Address',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
