# Generated by Django 3.2.16 on 2023-09-05 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Personalization', '0007_alter_images_image_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='Age',
        ),
        migrations.RemoveField(
            model_name='messages',
            name='Gender',
        ),
        migrations.AddField(
            model_name='messages',
            name='ViewerDetail_ID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Personalization.viewerdetail'),
            preserve_default=False,
        ),
    ]
