# Generated by Django 3.2.16 on 2023-09-05 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Personalization', '0008_auto_20230905_1340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='Age',
        ),
        migrations.RemoveField(
            model_name='images',
            name='Gender',
        ),
        migrations.AddField(
            model_name='images',
            name='ViewerDetail_ID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Personalization.viewerdetail'),
            preserve_default=False,
        ),
    ]
