# Generated by Django 3.2.16 on 2023-09-05 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Personalization', '0009_auto_20230905_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='URL',
        ),
    ]
