# Generated by Django 3.2.16 on 2023-09-05 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personalization', '0011_auto_20230905_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='Course',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='messages',
            name='Nationality',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
