# Generated by Django 3.2.16 on 2023-09-05 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personalization', '0013_remove_messages_location_identifier_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='Message_Parameters',
            field=models.CharField(default='20cm x 20cm', max_length=50),
        ),
    ]
