# Generated by Django 3.2.16 on 2023-09-05 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Personalization', '0014_alter_messages_message_parameters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='Display_ID',
        ),
        migrations.RemoveField(
            model_name='messages',
            name='Display_ID',
        ),
    ]
