# Generated by Django 3.2.16 on 2023-09-05 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personalization', '0016_auto_20230905_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='Age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='messages',
            name='Course',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='messages',
            name='Gender',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='messages',
            name='Nationality',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
