# Generated by Django 3.2.16 on 2023-09-05 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personalization', '0017_auto_20230905_2328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='ViewerDetail_ID',
        ),
        migrations.AddField(
            model_name='images',
            name='Age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='images',
            name='Course',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='images',
            name='Gender',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='images',
            name='Nationality',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
