# Generated by Django 3.2.16 on 2023-09-05 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Personalization', '0018_auto_20230905_2334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='displaydetail',
            name='Location_Identifier_ID',
        ),
        migrations.AddField(
            model_name='locationidentifier',
            name='DisplayDetails_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Personalization.displaydetail'),
        ),
    ]
